### ISSUE TITLE
Reduce rateStalePeriod

### ISSUE THREAD

**Issue by kevholder** [oikos-cash/oikos-bsc#1]
Reduce https://bscscan.com/address/0x9A1D6d7900eC1E34bF22f85a139a21461D4bFB42#readContract .. it's currently set at 3 hours which is too much.

**Comment by kevholder** [comment]
Also, change period for price feed script to be < rateStalePeriod

**Comment by oikos1** [comment]
Closing as this is an old issue and was taking care by Chainlink implementation.
